// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: rpc_flight.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RPCFlightClient is the client API for RPCFlight service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCFlightClient interface {
	CreateFlight(ctx context.Context, in *Flight, opts ...grpc.CallOption) (*Flight, error)
	UpdateFlight(ctx context.Context, in *Flight, opts ...grpc.CallOption) (*Flight, error)
	SearchFlight(ctx context.Context, in *SearchFlightRequest, opts ...grpc.CallOption) (*SearchFlightResponse, error)
}

type rPCFlightClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCFlightClient(cc grpc.ClientConnInterface) RPCFlightClient {
	return &rPCFlightClient{cc}
}

func (c *rPCFlightClient) CreateFlight(ctx context.Context, in *Flight, opts ...grpc.CallOption) (*Flight, error) {
	out := new(Flight)
	err := c.cc.Invoke(ctx, "/tuns_go_flight.RPCFlight/CreateFlight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCFlightClient) UpdateFlight(ctx context.Context, in *Flight, opts ...grpc.CallOption) (*Flight, error) {
	out := new(Flight)
	err := c.cc.Invoke(ctx, "/tuns_go_flight.RPCFlight/UpdateFlight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCFlightClient) SearchFlight(ctx context.Context, in *SearchFlightRequest, opts ...grpc.CallOption) (*SearchFlightResponse, error) {
	out := new(SearchFlightResponse)
	err := c.cc.Invoke(ctx, "/tuns_go_flight.RPCFlight/SearchFlight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCFlightServer is the server API for RPCFlight service.
// All implementations must embed UnimplementedRPCFlightServer
// for forward compatibility
type RPCFlightServer interface {
	CreateFlight(context.Context, *Flight) (*Flight, error)
	UpdateFlight(context.Context, *Flight) (*Flight, error)
	SearchFlight(context.Context, *SearchFlightRequest) (*SearchFlightResponse, error)
	mustEmbedUnimplementedRPCFlightServer()
}

// UnimplementedRPCFlightServer must be embedded to have forward compatible implementations.
type UnimplementedRPCFlightServer struct {
}

func (UnimplementedRPCFlightServer) CreateFlight(context.Context, *Flight) (*Flight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFlight not implemented")
}
func (UnimplementedRPCFlightServer) UpdateFlight(context.Context, *Flight) (*Flight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFlight not implemented")
}
func (UnimplementedRPCFlightServer) SearchFlight(context.Context, *SearchFlightRequest) (*SearchFlightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchFlight not implemented")
}
func (UnimplementedRPCFlightServer) mustEmbedUnimplementedRPCFlightServer() {}

// UnsafeRPCFlightServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCFlightServer will
// result in compilation errors.
type UnsafeRPCFlightServer interface {
	mustEmbedUnimplementedRPCFlightServer()
}

func RegisterRPCFlightServer(s grpc.ServiceRegistrar, srv RPCFlightServer) {
	s.RegisterService(&RPCFlight_ServiceDesc, srv)
}

func _RPCFlight_CreateFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Flight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCFlightServer).CreateFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tuns_go_flight.RPCFlight/CreateFlight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCFlightServer).CreateFlight(ctx, req.(*Flight))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCFlight_UpdateFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Flight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCFlightServer).UpdateFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tuns_go_flight.RPCFlight/UpdateFlight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCFlightServer).UpdateFlight(ctx, req.(*Flight))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCFlight_SearchFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCFlightServer).SearchFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tuns_go_flight.RPCFlight/SearchFlight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCFlightServer).SearchFlight(ctx, req.(*SearchFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCFlight_ServiceDesc is the grpc.ServiceDesc for RPCFlight service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCFlight_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tuns_go_flight.RPCFlight",
	HandlerType: (*RPCFlightServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFlight",
			Handler:    _RPCFlight_CreateFlight_Handler,
		},
		{
			MethodName: "UpdateFlight",
			Handler:    _RPCFlight_UpdateFlight_Handler,
		},
		{
			MethodName: "SearchFlight",
			Handler:    _RPCFlight_SearchFlight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_flight.proto",
}
